{
  "hash": "56fd80d15c249f6a4ae40b2c3b71cee0",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Extracting insights from job descriptions -- ML Methods\nauthor: Team 4\ndate: today\nformat:\n  html:\n    csl: csl/econometrica.csl\n    toc: true\n    css: styles.css\n    html-math-method: katex\n    embed-resources: false\n    code-fold: true\nexecute:\n  eval: true\n  echo: true\n---\n\n::: {#e568074a .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import OneHotEncoder\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.linear_model import LinearRegression\n\ndf = pd.read_csv(\"./data/lightcast_job_postings.csv\")\n\ncontinuous_cols = [\"MIN_YEARS_EXPERIENCE\", \"MAX_YEARS_EXPERIENCE\", \"SALARY_FROM\"]\ncategorical_cols = [\"EMPLOYMENT_TYPE_NAME\", \"STATE_NAME\"]\ntarget_col = \"SALARY\"\n\ndf = df.dropna(subset=continuous_cols + categorical_cols + [target_col])\nassert df[continuous_cols + categorical_cols + [target_col]].isna().sum().sum() == 0\n\ndf[\"MIN_YEARS_EXPERIENCE_SQ\"] = df[\"MIN_YEARS_EXPERIENCE\"] ** 2\n\nX = df[continuous_cols + [\"MIN_YEARS_EXPERIENCE_SQ\"] + categorical_cols]\ny = df[target_col]\n\npreprocessor = ColumnTransformer(transformers=[\n    (\"cat\", OneHotEncoder(handle_unknown=\"ignore\"), categorical_cols),\n    (\"num\", \"passthrough\", continuous_cols + [\"MIN_YEARS_EXPERIENCE_SQ\"])\n])\n\npipeline = Pipeline(steps=[\n    (\"preprocess\", preprocessor),\n    (\"model\", LinearRegression())\n])\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\npipeline.fit(X_train, y_train)\n\nprint(\"Train shape:\", X_train.shape)\nprint(\"Test shape:\", X_test.shape)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nC:\\Users\\11750\\AppData\\Local\\Temp\\ipykernel_12516\\462807244.py:10: DtypeWarning:\n\nColumns (19,30) have mixed types. Specify dtype option on import or set low_memory=False.\n\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nTrain shape: (3004, 6)\nTest shape: (752, 6)\n```\n:::\n:::\n\n\n# K-means ONET\n\n::: {#7775e904 .cell execution_count=2}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.cluster import KMeans\n\n# Load dataset\ndf = pd.read_csv(\"./data/lightcast_job_postings.csv\")\n\n# Select features for clustering\ncluster_features = [\"MIN_YEARS_EXPERIENCE\", \"MAX_YEARS_EXPERIENCE\", \"SALARY_FROM\"]\ndf_cluster = df.dropna(subset=cluster_features).copy()\n\n# Standardize the clustering features\nscaler = StandardScaler()\nX_scaled = scaler.fit_transform(df_cluster[cluster_features])\n\n# Apply KMeans\nkmeans = KMeans(n_clusters=4, random_state=42, n_init=10)\ndf_cluster[\"cluster\"] = kmeans.fit_predict(X_scaled)\n\n# Reference label comparison (e.g., ONET / SOC / NAICS)\nreference_col = \"ONET\"  # Replace with \"SOC\" or \"NAICS\" if needed\n\nif reference_col in df_cluster.columns:\n    cluster_reference_summary = (\n        df_cluster.groupby([\"cluster\", reference_col])\n        .size()\n        .reset_index(name=\"count\")\n        .sort_values([\"cluster\", \"count\"], ascending=[True, False])\n    )\n    print(f\"\\nTop {reference_col} codes by cluster:\")\n    print(cluster_reference_summary)\nelse:\n    print(f\"⚠️ Column '{reference_col}' not found in the dataset.\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nC:\\Users\\11750\\AppData\\Local\\Temp\\ipykernel_12516\\3264111928.py:7: DtypeWarning:\n\nColumns (19,30) have mixed types. Specify dtype option on import or set low_memory=False.\n\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nTop ONET codes by cluster:\n   cluster        ONET  count\n0        0  15-2051.01   1319\n1        1  15-2051.01    468\n2        2  15-2051.01    663\n3        3  15-2051.01   1488\n```\n:::\n:::\n\n\n::: {#bfbb0570 .cell execution_count=3}\n``` {.python .cell-code}\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\nsns.scatterplot(\n    data=df_cluster,\n    x=\"MIN_YEARS_EXPERIENCE\",\n    y=\"SALARY_FROM\",\n    hue=\"cluster\",\n    palette=\"tab10\"\n)\nplt.title(\"KMeans Clustering (colored by cluster)\")\nplt.xlabel(\"Min Years Experience\")\nplt.ylabel(\"Salary From\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ml_methods_files/figure-html/cell-4-output-1.png){width=618 height=449}\n:::\n:::\n\n\nWe used KMeans clustering to group job postings based on minimum experience, maximum experience, and starting salary. These features help reveal natural divisions in job types without using predefined labels. After scaling the variables, the model identified four clusters. Although the ONET code 15-2051.01 appeared frequently across all clusters, the differences in experience and salary levels showed clear patterns in how jobs are structured. For job seekers, this analysis helps clarify where their profile fits in the market and what kinds of roles align with their experience and salary expectations.\n\n# linear regression\n\n::: {#309bc15d .cell execution_count=4}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import OneHotEncoder\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.linear_model import LinearRegression\nfrom sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error\n\n# Load data\ndf = pd.read_csv(\"./data/lightcast_job_postings.csv\")\n\n# Select features\ncontinuous_cols = [\"MIN_YEARS_EXPERIENCE\", \"MAX_YEARS_EXPERIENCE\", \"SALARY_FROM\"]\ncategorical_cols = [\"EMPLOYMENT_TYPE_NAME\", \"STATE_NAME\"]\ntarget_col = \"SALARY\"\n\n# Clean data\ndf = df.dropna(subset=continuous_cols + categorical_cols + [target_col])\ndf[\"MIN_YEARS_EXPERIENCE_SQ\"] = df[\"MIN_YEARS_EXPERIENCE\"] ** 2\n\n# Define X and y\nX = df[continuous_cols + [\"MIN_YEARS_EXPERIENCE_SQ\"] + categorical_cols]\ny = df[target_col]\n\n# Preprocessing\npreprocessor = ColumnTransformer(transformers=[\n    (\"cat\", OneHotEncoder(handle_unknown=\"ignore\"), categorical_cols),\n    (\"num\", \"passthrough\", continuous_cols + [\"MIN_YEARS_EXPERIENCE_SQ\"])\n])\n\n# Pipeline with Linear Regression\npipeline = Pipeline(steps=[\n    (\"preprocess\", preprocessor),\n    (\"model\", LinearRegression())\n])\n\n# Train-test split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\n# Train model\npipeline.fit(X_train, y_train)\n\n# Predict\ny_pred = pipeline.predict(X_test)\n\n# Evaluation\nr2 = r2_score(y_test, y_pred)\nmse = mean_squared_error(y_test, y_pred)\nrmse = np.sqrt(mse)\nmae = mean_absolute_error(y_test, y_pred)\n\nprint(\"Model Evaluation:\")\nprint(f\"R²:   {r2:.4f}\")\nprint(f\"RMSE: {rmse:.2f}\")\nprint(f\"MAE:  {mae:.2f}\")\n\n# Coefficients\nmodel = pipeline.named_steps[\"model\"]\nohe = pipeline.named_steps[\"preprocess\"].named_transformers_[\"cat\"]\ncat_feature_names = ohe.get_feature_names_out([\"EMPLOYMENT_TYPE_NAME\", \"STATE_NAME\"])\nall_features = list(cat_feature_names) + [\"MIN_YEARS_EXPERIENCE\", \"MAX_YEARS_EXPERIENCE\", \"SALARY_FROM\", \"MIN_YEARS_EXPERIENCE_SQ\"]\n\ncoef_df = pd.DataFrame({\n    \"Feature\": all_features,\n    \"Coefficient\": model.coef_\n}).sort_values(by=\"Coefficient\", key=lambda x: abs(x), ascending=False)\n\nprint(\"\\nTop 10 Influential Features:\")\nprint(coef_df.head(10))\n\n# Actual vs Predicted Plot\nplt.figure(figsize=(6, 6))\nplt.scatter(y_test, y_pred, alpha=0.5)\nplt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], \"r--\")\nplt.xlabel(\"Actual Salary\")\nplt.ylabel(\"Predicted Salary\")\nplt.title(\"Actual vs Predicted Salary\")\nplt.grid(True)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nC:\\Users\\11750\\AppData\\Local\\Temp\\ipykernel_12516\\932958033.py:12: DtypeWarning:\n\nColumns (19,30) have mixed types. Specify dtype option on import or set low_memory=False.\n\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nModel Evaluation:\nR²:   0.8869\nRMSE: 12334.44\nMAE:  9428.34\n\nTop 10 Influential Features:\n                                          Feature  Coefficient\n54                           MIN_YEARS_EXPERIENCE  1574.523361\n55                           MAX_YEARS_EXPERIENCE  1574.523361\n0     EMPLOYMENT_TYPE_NAME_Full-time (> 32 hours)  -354.484423\n2      EMPLOYMENT_TYPE_NAME_Part-time / full-time   181.798145\n1   EMPLOYMENT_TYPE_NAME_Part-time (â‰¤ 32 hours)   172.686278\n45                               STATE_NAME_Texas  -144.594249\n34                            STATE_NAME_New York   126.792998\n27                            STATE_NAME_Missouri   122.079562\n32                          STATE_NAME_New Jersey  -114.092170\n57                        MIN_YEARS_EXPERIENCE_SQ  -109.909633\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](ml_methods_files/figure-html/cell-5-output-3.png){width=566 height=566}\n:::\n:::\n\n\nWe used a linear regression model to predict job salary based on both numeric features (minimum and maximum experience, salary floor) and categorical features like employment type and state. After fitting the model, we found an R² of 0.8869, indicating strong predictive power. The most influential variables included years of experience and full-time employment type, both of which had a clear impact on predicted salary. The plot of actual vs. predicted salaries shows the model closely tracks real values, especially in the mid-range, with some underestimation at the highest salaries. This model helps job seekers understand which factors most affect salary and offers a data-backed view of how their profile may translate into pay.\n\n# Polynomial Regression\n\n::: {#a6651fcd .cell execution_count=5}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom sklearn.linear_model import LinearRegression\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.preprocessing import OneHotEncoder, PolynomialFeatures, StandardScaler\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error\n\n# Load dataset\ndf = pd.read_csv(\"./data/lightcast_job_postings.csv\")\n\n# Define columns\ncategorical_cols = [\"EMPLOYMENT_TYPE_NAME\", \"STATE_NAME\"]\nnumeric_cols = [\"MIN_YEARS_EXPERIENCE\", \"MAX_YEARS_EXPERIENCE\", \"SALARY_FROM\"]\ntarget_col = \"SALARY\"\n\n# Drop missing values\ndf = df.dropna(subset=numeric_cols + categorical_cols + [target_col])\n\n# Set features and target\nX = df[numeric_cols + categorical_cols]\ny = df[target_col]\n\n# Preprocessing pipeline\npreprocessor = ColumnTransformer([\n    (\"cat\", OneHotEncoder(drop=\"first\", handle_unknown=\"ignore\"), categorical_cols),\n    (\"num\", Pipeline([\n        (\"poly\", PolynomialFeatures(degree=2, include_bias=False)),  # 2nd-degree polynomial\n        (\"scale\", StandardScaler())\n    ]), numeric_cols)\n])\n\n# Build model pipeline\npipeline = Pipeline([\n    (\"preprocess\", preprocessor),\n    (\"model\", LinearRegression())\n])\n\n# Train/test split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\n# Fit model\npipeline.fit(X_train, y_train)\n\n# Predict\ny_pred = pipeline.predict(X_test)\n\n# Evaluate model\nr2 = r2_score(y_test, y_pred)\nrmse = np.sqrt(mean_squared_error(y_test, y_pred))  # version-safe RMSE\nmae = mean_absolute_error(y_test, y_pred)\n\nprint(\"Polynomial Regression Evaluation:\")\nprint(f\"R²:   {r2:.4f}\")\nprint(f\"RMSE: {rmse:.2f}\")\nprint(f\"MAE:  {mae:.2f}\")\n\n# Plot: Actual vs Predicted\nplt.figure(figsize=(6, 6))\nplt.scatter(y_test, y_pred, alpha=0.5)\nplt.plot([y.min(), y.max()], [y.min(), y.max()], \"r--\")\nplt.xlabel(\"Actual Salary\")\nplt.ylabel(\"Predicted Salary\")\nplt.title(\"Polynomial Regression: Actual vs. Predicted Salary\")\nplt.grid(True)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nC:\\Users\\11750\\AppData\\Local\\Temp\\ipykernel_12516\\1802226215.py:12: DtypeWarning:\n\nColumns (19,30) have mixed types. Specify dtype option on import or set low_memory=False.\n\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nPolynomial Regression Evaluation:\nR²:   0.8977\nRMSE: 11728.64\nMAE:  9060.18\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](ml_methods_files/figure-html/cell-6-output-3.png){width=566 height=566}\n:::\n:::\n\n\nWe used polynomial regression to predict salary based on numeric features like experience and salary floor, while also accounting for interactions and non-linear effects using second-degree polynomial terms. The model achieved an R² of 0.8977, slightly outperforming linear regression, with a lower RMSE and MAE. The prediction plot shows a strong alignment between actual and predicted values, especially for mid-range salaries, while still handling higher salaries more flexibly than a standard linear fit. For job seekers, this model highlights how the relationship between experience and salary is not always linear and suggests that salary growth accelerates or flattens depending on experience level.\n\n# Random Forest Regressor\n\n::: {#f6d967b5 .cell execution_count=6}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import OneHotEncoder\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.ensemble import RandomForestRegressor\nfrom sklearn.metrics import mean_squared_error, r2_score\n\n# Load dataset\ndf = pd.read_csv(\"./data/lightcast_job_postings.csv\")\n\n# Define relevant columns\ncontinuous_cols = [\"MIN_YEARS_EXPERIENCE\", \"MAX_YEARS_EXPERIENCE\", \"SALARY_FROM\"]\ncategorical_cols = [\"EMPLOYMENT_TYPE_NAME\", \"STATE_NAME\"]\ntarget_col = \"SALARY\"\n\n# Drop rows with missing values in required columns\ndf = df.dropna(subset=continuous_cols + categorical_cols + [target_col])\n\n# Add a quadratic term for better non-linear modeling\ndf[\"MIN_YEARS_EXPERIENCE_SQ\"] = df[\"MIN_YEARS_EXPERIENCE\"] ** 2\n\n# Define features (X) and target (y)\nX = df[continuous_cols + [\"MIN_YEARS_EXPERIENCE_SQ\"] + categorical_cols]\ny = df[target_col]\n\n# Preprocessing pipeline: One-hot encode categoricals, passthrough numerics\npreprocessor = ColumnTransformer(transformers=[\n    (\"cat\", OneHotEncoder(handle_unknown=\"ignore\"), categorical_cols),\n    (\"num\", \"passthrough\", continuous_cols + [\"MIN_YEARS_EXPERIENCE_SQ\"])\n])\n\n# Full pipeline: preprocessing + random forest model\npipeline = Pipeline(steps=[\n    (\"preprocess\", preprocessor),\n    (\"model\", RandomForestRegressor(n_estimators=100, random_state=42))\n])\n\n# Split dataset into training and testing sets\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\n# Train the model\npipeline.fit(X_train, y_train)\n\n# Predict on test set\ny_pred = pipeline.predict(X_test)\n\n# Evaluate performance\nrmse = np.sqrt(mean_squared_error(y_test, y_pred))  # compatible RMSE calculation\nr2 = r2_score(y_test, y_pred)\n\n# Output metrics\nprint(f\"RMSE: {rmse:.2f}\")\nprint(f\"R² Score: {r2:.3f}\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nC:\\Users\\11750\\AppData\\Local\\Temp\\ipykernel_12516\\1632232137.py:11: DtypeWarning:\n\nColumns (19,30) have mixed types. Specify dtype option on import or set low_memory=False.\n\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nRMSE: 8811.35\nR² Score: 0.942\n```\n:::\n:::\n\n\n::: {#2cb8575f .cell execution_count=7}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\n# Get trained model and feature names\nmodel = pipeline.named_steps[\"model\"]\nfeature_names = pipeline.named_steps[\"preprocess\"].get_feature_names_out()\n\n# Get feature importances\nimportances = model.feature_importances_\n\n# Get top 10 features\ntop_idx = np.argsort(importances)[-10:]\ntop_features = np.array(feature_names)[top_idx]\ntop_importances = importances[top_idx]\n\n# Plot\nplt.figure(figsize=(8, 5))\nplt.barh(top_features, top_importances)\nplt.xlabel(\"Feature Importance\")\nplt.title(\"Top 10 Important Features in Salary Prediction\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ml_methods_files/figure-html/cell-8-output-1.png){width=759 height=470}\n:::\n:::\n\n\nWe used a Random Forest regression model to predict job salaries based on experience, employment type, and location. This model outperformed both linear and polynomial regression with an R² of 0.942 and an RMSE of 8811.35, showing high accuracy in capturing complex relationships between features and salary. The feature importance plot shows that the starting salary field (SALARY_FROM) is by far the most influential input, followed by years of experience and job location. For job seekers, this model helps identify which factors have the most impact on expected salary and supports more informed decisions when evaluating or negotiating job offers.\n\n\n# Logistic Regression & Random Forest Classifier\n\n::: {#09123475 .cell execution_count=8}\n``` {.python .cell-code}\nimport pandas as pd\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import OneHotEncoder, StandardScaler\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.metrics import classification_report, accuracy_score\n\n# Load data\ndf = pd.read_csv(\"./data/lightcast_job_postings.csv\")\n\n# Set target to NAICS2\ntarget_col = \"NAICS2\"\ncategorical_cols = [\"EMPLOYMENT_TYPE_NAME\", \"STATE_NAME\"]\nnumeric_cols = [\"MIN_YEARS_EXPERIENCE\", \"MAX_YEARS_EXPERIENCE\", \"SALARY_FROM\"]\n\n# Drop rows with missing values\ndf = df.dropna(subset=numeric_cols + categorical_cols + [target_col])\n\n# Filter to classes with at least 50 samples\nclass_counts = df[target_col].value_counts()\nvalid_classes = class_counts[class_counts >= 50].index\n\nif len(valid_classes) < 2:\n    raise ValueError(\"Not enough valid NAICS2 classes for classification.\")\n\ndf = df[df[target_col].isin(valid_classes)]\n\n# Print classes being used\nprint(\"Classes used:\", df[target_col].unique())\n\n# Define features and target\nX = df[numeric_cols + categorical_cols]\ny = df[target_col]\n\n# Preprocessing pipeline\npreprocessor = ColumnTransformer([\n    (\"cat\", OneHotEncoder(handle_unknown=\"ignore\"), categorical_cols),\n    (\"num\", StandardScaler(), numeric_cols)\n])\n\n# Train-test split (80/20 stratified)\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.2, random_state=42, stratify=y\n)\n\n# Logistic Regression pipeline\nlogit_pipeline = Pipeline([\n    (\"preprocess\", preprocessor),\n    (\"model\", LogisticRegression(max_iter=1000, multi_class=\"multinomial\"))\n])\n\nlogit_pipeline.fit(X_train, y_train)\ny_pred_logit = logit_pipeline.predict(X_test)\n\nprint(\"\\n=== Logistic Regression ===\")\nprint(classification_report(y_test, y_pred_logit))\nprint(f\"Accuracy: {accuracy_score(y_test, y_pred_logit):.4f}\")\n\n# Random Forest pipeline\nrf_pipeline = Pipeline([\n    (\"preprocess\", preprocessor),\n    (\"model\", RandomForestClassifier(n_estimators=100, random_state=42))\n])\n\nrf_pipeline.fit(X_train, y_train)\ny_pred_rf = rf_pipeline.predict(X_test)\n\nprint(\"\\n=== Random Forest Classifier ===\")\nprint(classification_report(y_test, y_pred_rf))\nprint(f\"Accuracy: {accuracy_score(y_test, y_pred_rf):.4f}\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nC:\\Users\\11750\\AppData\\Local\\Temp\\ipykernel_12516\\1685128331.py:11: DtypeWarning:\n\nColumns (19,30) have mixed types. Specify dtype option on import or set low_memory=False.\n\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nClasses used: [54. 62. 56. 61. 52. 99. 44. 42. 31. 51. 53. 23.]\n\n=== Logistic Regression ===\n              precision    recall  f1-score   support\n\n        23.0       0.00      0.00      0.00        15\n        31.0       0.00      0.00      0.00        30\n        42.0       0.36      0.41      0.39        75\n        44.0       0.50      0.19      0.28        21\n        51.0       0.30      0.05      0.09        55\n        52.0       0.30      0.41      0.35       123\n        53.0       0.00      0.00      0.00        21\n        54.0       0.30      0.72      0.43       185\n        56.0       0.00      0.00      0.00        79\n        61.0       0.23      0.11      0.15        28\n        62.0       0.00      0.00      0.00        34\n        99.0       0.39      0.08      0.14        84\n\n    accuracy                           0.31       750\n   macro avg       0.20      0.17      0.15       750\nweighted avg       0.25      0.31      0.24       750\n\nAccuracy: 0.3107\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nC:\\Repositories\\ad688-employability-sp25A1-group4.io-11\\.venv\\lib\\site-packages\\sklearn\\linear_model\\_logistic.py:1247: FutureWarning:\n\n'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.\n\nC:\\Repositories\\ad688-employability-sp25A1-group4.io-11\\.venv\\lib\\site-packages\\sklearn\\metrics\\_classification.py:1565: UndefinedMetricWarning:\n\nPrecision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n\nC:\\Repositories\\ad688-employability-sp25A1-group4.io-11\\.venv\\lib\\site-packages\\sklearn\\metrics\\_classification.py:1565: UndefinedMetricWarning:\n\nPrecision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n\nC:\\Repositories\\ad688-employability-sp25A1-group4.io-11\\.venv\\lib\\site-packages\\sklearn\\metrics\\_classification.py:1565: UndefinedMetricWarning:\n\nPrecision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.\n\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n=== Random Forest Classifier ===\n              precision    recall  f1-score   support\n\n        23.0       0.55      0.73      0.63        15\n        31.0       0.35      0.27      0.30        30\n        42.0       0.75      0.76      0.75        75\n        44.0       0.38      0.29      0.32        21\n        51.0       0.53      0.47      0.50        55\n        52.0       0.64      0.66      0.65       123\n        53.0       0.60      0.57      0.59        21\n        54.0       0.55      0.63      0.59       185\n        56.0       0.51      0.38      0.43        79\n        61.0       0.49      0.64      0.55        28\n        62.0       0.35      0.35      0.35        34\n        99.0       0.30      0.27      0.29        84\n\n    accuracy                           0.53       750\n   macro avg       0.50      0.50      0.50       750\nweighted avg       0.53      0.53      0.53       750\n\nAccuracy: 0.5347\n```\n:::\n:::\n\n\n::: {#bf8a3868 .cell execution_count=9}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\nimport numpy as np\n\n# Random Forest feature importances\nrf_features = rf_pipeline.named_steps[\"preprocess\"].get_feature_names_out()\nrf_importances = rf_pipeline.named_steps[\"model\"].feature_importances_\n\n# Top 15\nrf_top_idx = np.argsort(rf_importances)[-15:]\nplt.figure(figsize=(8, 6))\nplt.barh(np.array(rf_features)[rf_top_idx], rf_importances[rf_top_idx])\nplt.title(\"Top 15 Important Features - Random Forest\")\nplt.xlabel(\"Feature Importance\")\nplt.grid(True, axis=\"x\", linestyle=\"--\", alpha=0.5)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ml_methods_files/figure-html/cell-10-output-1.png){width=757 height=566}\n:::\n:::\n\n\n::: {#3fe4052a .cell execution_count=10}\n``` {.python .cell-code}\n# Logistic Regression coefficients\nlogit_features = logit_pipeline.named_steps[\"preprocess\"].get_feature_names_out()\nlogit_coefs = logit_pipeline.named_steps[\"model\"].coef_\n\n# Mean absolute value across classes\nlogit_importance = np.mean(np.abs(logit_coefs), axis=0)\n\n# Top 15\nlogit_top_idx = np.argsort(logit_importance)[-15:]\nplt.figure(figsize=(8, 6))\nplt.barh(np.array(logit_features)[logit_top_idx], logit_importance[logit_top_idx])\nplt.title(\"Top 15 Feature Coefficients - Logistic Regression\")\nplt.xlabel(\"Average |Coefficient| Across Classes\")\nplt.grid(True, axis=\"x\", linestyle=\"--\", alpha=0.5)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](ml_methods_files/figure-html/cell-11-output-1.png){width=759 height=567}\n:::\n:::\n\n\nThe Random Forest classifier outperformed Logistic Regression in classifying job postings by NAICS2 industry code, achieving 53.5% accuracy compared to Logistic Regression’s 31%. The Random Forest model identified salary-related numeric features like SALARY_FROM, MAX_YEARS_EXPERIENCE, and MIN_YEARS_EXPERIENCE as the most influential, while Logistic Regression emphasized categorical features such as state-level job locations. The poor performance of Logistic Regression is likely due to its linear nature and inability to capture complex patterns, especially in a multi-class problem with subtle feature interactions. In contrast, Random Forest leveraged both numeric and categorical features more effectively, making it the better choice for this classification task.\n\n",
    "supporting": [
      "ml_methods_files"
    ],
    "filters": [],
    "includes": {}
  }
}